name: Generate and Deploy Chart (Main Branch Only)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
        # Optionally, skip building if it's the workflow bot's own commit
        # to avoid infinite loop:
        # if: "! contains(github.event.head_commit.message, '[skip-ci]')"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate plot
        run: python plot_trades.py
        # Suppose your script now directly writes 'index.html' + 'latest_plot.png'
        # in the repository root rather than "out/" folder

      - name: Commit updated site
        run: |
           git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/index.html out/latest_plot.png
          git commit -m "Update chart [skip-ci]" || echo "No changes to commit"
          git push
