name: Generate and Deploy Chart (Main Branch Only)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate plot
        run: python plot_trades.py

      - name: Commit updated site
        run: |
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage our out/ folder (with index.html + PNG)
          git add out/index.html out/latest_plot.png
          
          # Commit if there's a change
          git commit -m "Update chart [skip-ci]" || echo "No changes to commit"
          
          # Push back to main
          git push
