name: Generate and Deploy Chart (Main Branch Only)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate stock data and plot
        run: python plot_trades.py

      - name: Commit updated data and plot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/stock_data.csv out/index.html out/latest_plot_large.png
          git commit -m "Update chart & stock data [skip-ci]" || echo "No changes to commit"
          git push
